# Generated by Django 5.1.2 on 2025-02-17 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad', models.CharField(choices=[('F', 'Fácil'), ('N', 'Normal'), ('D', 'Difícil')], default='N', max_length=1)),
                ('partida_terminada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('contrasena', models.CharField(max_length=120)),
                ('partidas_jugadas', models.FloatField(default=0)),
                ('partidas_ganadas', models.FloatField(default=0)),
                ('session_token', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Roca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField()),
                ('Y', models.IntegerField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roca_partida', to='flotaapp.partida')),
            ],
        ),
        migrations.CreateModel(
            name='SesionesUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='flotaapp.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_ganador', to='flotaapp.usuarios'),
        ),
        migrations.AddField(
            model_name='partida',
            name='turno_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_actual', to='flotaapp.usuarios'),
        ),
        migrations.AddField(
            model_name='partida',
            name='usuario1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_usuario1', to='flotaapp.usuarios'),
        ),
        migrations.AddField(
            model_name='partida',
            name='usuario2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_usuario2', to='flotaapp.usuarios'),
        ),
        migrations.CreateModel(
            name='Emparejamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad', models.CharField(choices=[('F', 'Fácil'), ('N', 'Normal'), ('D', 'Difícil')], default='N', max_length=1)),
                ('usuario1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emparejamiento_usuario1', to='flotaapp.usuarios')),
                ('usuario2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emparejamiento_usuario2', to='flotaapp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='BarcosPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField()),
                ('Y', models.IntegerField()),
                ('direccion', models.CharField(choices=[('H', 'horizontal'), ('V', 'vertical')], default='V', max_length=1)),
                ('tipo_barco', models.IntegerField(choices=[(0, 'Patrullero'), (1, 'Destructor'), (2, 'Submarino'), (3, 'Acorazado'), (4, 'Portaaviones')])),
                ('hundido', models.BooleanField(default=False)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcos_partida', to='flotaapp.partida')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcos_jugador', to='flotaapp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Ataques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField()),
                ('Y', models.IntegerField()),
                ('resultado', models.IntegerField(choices=[(0, 'Patrullero'), (1, 'Destructor'), (2, 'Submarino'), (3, 'Acorazado'), (4, 'Portaaviones'), (5, 'Agua')])),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques_partida', to='flotaapp.partida')),
                ('atacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques_atacante', to='flotaapp.usuarios')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques_objetivo', to='flotaapp.usuarios')),
            ],
        ),
    ]
