# Generated by Django 4.0.10 on 2025-01-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flotaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emparejamiento',
            name='usuario1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emparejamiento_usuario1', to='flotaapp.usuarios'),
        ),
        migrations.AlterField(
            model_name='emparejamiento',
            name='usuario2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emparejamiento_usuario2', to='flotaapp.usuarios'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='usuario1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_usuario1', to='flotaapp.usuarios'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='usuario2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_usuario2', to='flotaapp.usuarios'),
        ),
    ]
