# Generated by Django 4.0.10 on 2025-01-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flotaapp', '0002_alter_emparejamiento_usuario1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emparejamiento',
            name='es_mutuo',
        ),
    ]
