# Generated by Django 4.0.10 on 2025-01-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotaapp', '0004_sesionesusuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcospartida',
            name='hundido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='session_token',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ataques',
            name='resultado',
            field=models.IntegerField(choices=[(0, 'Patrullero'), (1, 'Destructor'), (2, 'Submarino'), (3, 'Acorazado'), (4, 'Portaaviones'), (5, 'Agua')]),
        ),
        migrations.AlterField(
            model_name='barcospartida',
            name='tipo_barco',
            field=models.IntegerField(choices=[(0, 'Patrullero'), (1, 'Destructor'), (2, 'Submarino'), (3, 'Acorazado'), (4, 'Portaaviones')]),
        ),
    ]
